env:
  global:
  - HEROKU_TEST_APP_NAME="heroku-deploy-plugin-test"
  - secure: VfQ5tSDLl4MYAnSpO9lOZCezML6HZ1Kny/JE2myTrxaW5v5oIXE8c6Cn3ZCvOwsPbTrSoEPMJcHq+M55UhDpzcWCGatfrkLrZ/qAF3TC98ZIKwVbvf66rB+gd1SMG1hAIXaJeu8a3scPbRx1zybtJC6GUVHNFNKgj7Qv7dhneBg=
language: ruby
install:
- "./etc/travis-setup.sh"
- bundle install
script: bundle exec rspec
after_script: heroku keys:remove $USER@`hostname`
