env:
  global:
  - HEROKU_TEST_APP_NAME="heroku-deploy-plugin-test"
  - secure: Zmiy4Aw+AYAEFAtgYiUNaEfGRKqsn4E668In2uuDpJ8K8A932PQgnKs+wAINGzWX1YOGVfqvNmT1xiJdHy3c0kS9P0KHAizqNxnbnbfofV8djRM5aQOiZb6v3RP+zt2zgUdewv2wHdGUFt3raVDU50JVMkJ/Nw11l+V1VojzgBo=
language: ruby
rvm:
- 2.2.3
install:
- "./etc/travis-setup.sh"
- bundle install
script: bundle exec rspec
after_script: heroku keys:remove $USER@`hostname`
