env:
  global:
  - HEROKU_TEST_APP_NAME="heroku-deploy-plugin-test"
  - secure: oa2H5hF7FDq4dbYRaA8etk1C2ju+5nmKN51oxKnwh6vi7MhZXPUhc3oTNQCqjg/Dq91xKcakgSU+vRQ2uxPfomdaPBrZKL+1zHCER8fI3CJoVQyPnBCX2t8RuXWzI9gVYQmxk4OMVFBK176bUo0kmeFmRCqMC45DuVEqqtFwB70=
language: ruby
install:
- "./etc/travis-setup.sh"
- bundle install
script: bundle exec rspec
after_script: heroku keys:remove $USER@`hostname`
